import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";
import type { seedDatabase } from "../../utils/seed";
import { logger } from "#/lib/logger";

// Store seeded users for test access
let seededUsers: Awaited<ReturnType<typeof seedDatabase>> | null = null;
let seedingPromise: Promise<void> | null = null;

async function createDb() {
	const isTest = process.env.NODE_ENV === "test" || process.env.VITEST === "true";
	const usePglite = process.env.USE_PGLITE === "true";
	const shouldLog = process.env.DB_LOGGING === "true";

	if (isTest || usePglite) {
		// Dynamic imports to avoid loading native modules on unsupported platforms (e.g., Windows ARM64)
		const { PGlite } = await import("@electric-sql/pglite");
		const { drizzle: drizzlePglite } = await import("drizzle-orm/pglite");
		const { migrate } = await import("drizzle-orm/pglite/migrator");
		const fs = await import("fs");

		// Use file-based persistence in dev mode, in-memory for tests
		const dataDir = isTest ? undefined : "./.pglite-data";
		const isNewDb = dataDir ? !fs.existsSync(dataDir) : true;
		logger.info({ dataDir, isNewDb }, dataDir ? "Setting up PGlite with persistent storage" : "Setting up PGlite in-memory database");
		const pglite = new PGlite(dataDir);
		const db = drizzlePglite(pglite, { schema, logger: shouldLog });

		// Run migrations
		logger.info("Running migrations...");
		await migrate(db as any, { migrationsFolder: "./src/drizzle" });
		logger.info("Migrations complete");

		// Manually create training tables that were skipped due to PGlite incompatibility
		// These migrations (0026, 0027) use DO $ blocks which don't work in PGlite prepared statements
		logger.info("Creating training tables for PGlite...");
		try {
			// Create enums first
			await pglite.exec(`
				DO $$ BEGIN
					CREATE TYPE training_assignment_status AS ENUM ('pending', 'in_progress', 'completed');
				EXCEPTION
					WHEN duplicate_object THEN null;
				END $$;
			`);
			await pglite.exec(`
				DO $$ BEGIN
					CREATE TYPE training_assignment_priority AS ENUM ('low', 'normal', 'high');
				EXCEPTION
					WHEN duplicate_object THEN null;
				END $$;
			`);
			await pglite.exec(`
				DO $$ BEGIN
					CREATE TYPE training_assignment_source AS ENUM ('flag', 'skill_threshold', 'battle_card', 'manual');
				EXCEPTION
					WHEN duplicate_object THEN null;
				END $$;
			`);
			await pglite.exec(`
				DO $$ BEGIN
					CREATE TYPE training_type AS ENUM ('scenario', 'battle_card', 'flag_review');
				EXCEPTION
					WHEN duplicate_object THEN null;
				END $$;
			`);
			await pglite.exec(`
				DO $$ BEGIN
					CREATE TYPE training_session_status AS ENUM ('in_progress', 'completed');
				EXCEPTION
					WHEN duplicate_object THEN null;
				END $$;
			`);

			// Create training_assignments table
			await pglite.exec(`
				CREATE TABLE IF NOT EXISTS training_assignments (
					id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
					salesperson_id integer NOT NULL REFERENCES salespeople(id) ON DELETE CASCADE,
					company_id integer NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
					assignment_source training_assignment_source NOT NULL,
					source_id text,
					training_type training_type NOT NULL,
					training_id text NOT NULL,
					title text NOT NULL,
					description text,
					priority training_assignment_priority DEFAULT 'normal',
					assigned_by text REFERENCES "user"(id) ON DELETE SET NULL,
					due_date timestamp,
					status training_assignment_status NOT NULL DEFAULT 'pending',
					completed_at timestamp,
					created_at timestamp NOT NULL DEFAULT NOW(),
					updated_at timestamp NOT NULL DEFAULT NOW()
				);
			`);

			// Create training_sessions_completed table
			await pglite.exec(`
				CREATE TABLE IF NOT EXISTS training_sessions_completed (
					id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
					scenario_id integer NOT NULL REFERENCES training_scenarios(id) ON DELETE CASCADE,
					salesperson_id integer NOT NULL REFERENCES salespeople(id) ON DELETE CASCADE,
					agent_id text,
					agent_prompt jsonb,
					status training_session_status NOT NULL DEFAULT 'in_progress',
					started_at timestamp NOT NULL DEFAULT NOW(),
					completed_at timestamp,
					training_session jsonb,
					created_at timestamp NOT NULL DEFAULT NOW(),
					updated_at timestamp NOT NULL DEFAULT NOW()
				);
			`);
			// Create partial unique index (can't have in CREATE TABLE since it's conditional)
			await pglite.exec(`
				CREATE UNIQUE INDEX IF NOT EXISTS unique_in_progress_session_idx
				ON training_sessions_completed (salesperson_id, scenario_id)
				WHERE status = 'in_progress';
			`);

			// Add first_message column to training_scenarios (migration 0034)
			await pglite.exec(`
				ALTER TABLE training_scenarios ADD COLUMN IF NOT EXISTS first_message text;
			`);

			// Create battle_card_status enum and battle_cards table (migration 0034)
			await pglite.exec(`
				DO $$ BEGIN
					CREATE TYPE battle_card_status AS ENUM ('draft', 'active', 'archived');
				EXCEPTION
					WHEN duplicate_object THEN null;
				END $$;
			`);

			await pglite.exec(`
				CREATE TABLE IF NOT EXISTS battle_cards (
					id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
					company_id integer NOT NULL REFERENCES company(id) ON DELETE CASCADE,
					title text NOT NULL,
					challenge text NOT NULL,
					phase sales_phase NOT NULL,
					strategy text NOT NULL,
					approach jsonb NOT NULL,
					script text NOT NULL,
					next_step text NOT NULL,
					source_type text NOT NULL,
					source_id integer,
					frequency integer DEFAULT 0 NOT NULL,
					success_rate numeric(5, 2),
					impact_score numeric(5, 2),
					status battle_card_status DEFAULT 'active' NOT NULL,
					difficulty_level integer DEFAULT 1 NOT NULL,
					is_active boolean DEFAULT true NOT NULL,
					linked_scenario_id integer REFERENCES training_scenarios(id) ON DELETE SET NULL,
					created_at timestamp DEFAULT NOW() NOT NULL,
					updated_at timestamp DEFAULT NOW() NOT NULL
				);
			`);

			logger.info("Training tables created successfully");
		} catch (error) {
			logger.warn({ error }, "Error creating training tables (may already exist)");
		}

		// Add training_session column to flags (migration 0042 equivalent)
		try {
			await pglite.exec(`
				ALTER TABLE flags ADD COLUMN IF NOT EXISTS training_session JSONB;
			`);
		} catch (error) {
			logger.warn({ error }, "Error adding training_session to flags (may already exist)");
		}

		// Add query indexes for common patterns (migration 0044 equivalent)
		try {
			await pglite.exec(`
				CREATE INDEX IF NOT EXISTS interactions_salesperson_status_idx
				ON interactions(salesperson_id, processed_status);
			`);
			await pglite.exec(`
				CREATE INDEX IF NOT EXISTS flags_salesperson_complete_idx
				ON flags(associated_salesperson_id, complete);
			`);
			await pglite.exec(`
				CREATE INDEX IF NOT EXISTS interaction_objections_agg_idx
				ON interaction_objections(objection_id, was_overcome, created_at);
			`);
			await pglite.exec(`
				CREATE INDEX IF NOT EXISTS interaction_pain_points_agg_idx
				ON interaction_pain_points(pain_point_id, was_resolved, created_at);
			`);
		} catch (error) {
			logger.warn({ error }, "Error creating indexes (may already exist)");
		}

		// Seed the database only if it's new (async to avoid circular dependency with auth)
		if (isNewDb) {
			seedingPromise = import("../../utils/seed.js").then(async ({ seedDatabase }) => {
				logger.info("Seeding database...");
				seededUsers = await seedDatabase(db);
				logger.info("Database seeded");
			});
		} else {
			logger.info("Using existing database - skipping seed");
		}

		return db;
	}

	// Production postgres configuration
	const { DB_HOST, DB_USER, DB_PASSWORD, DB_DATABASE } = process.env;

	logger.info(
		{ DB_HOST, DB_USER, DB_DATABASE, DB_PASSWORD: `password len > 0 ${DB_PASSWORD ? DB_PASSWORD.length > 0 : "NO PASSWORD"}` },
		"Setting up Postgres connection I think",
	);
	if (!DB_HOST || !DB_USER || !DB_PASSWORD || !DB_DATABASE) {
		throw new Error("Missing required database environment variables: DB_HOST, DB_USER, DB_PASSWORD, DB_DATABASE");
	}

	const client = postgres({
		prepare: false,
		host: DB_HOST,
		username: DB_USER,
		password: DB_PASSWORD,
		database: DB_DATABASE,
		port: 5432,
	});

	await client`select 1`
		.then(() => {
			logger.info("Postgres connection successful");
		})
		.catch((err) => {
			logger.error({ err }, "Postgres connection error");
			throw err;
		});

	const db = drizzle({ logger: shouldLog, client, schema });
	return db;
}

export type OurDb = Awaited<ReturnType<typeof createDb>>;

export const _db = await createDb();

export const db = new Proxy(_db, {});
export { seededUsers as users };
export const usersReady = seedingPromise ?? Promise.resolve();

/**
 * Converts seconds to HH:MM:SS format
 */
function formatTimestamp(seconds: number): string {
	const hours = Math.floor(seconds / 3600);
	const minutes = Math.floor((seconds % 3600) / 60);
	const secs = Math.floor(seconds % 60);
	return `${hours.toString().padStart(2, "0")}:${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
}

/**
 * Computes the rawInteractionText from an interaction's structured data
 * This is used to maintain backward compatibility while removing the stored field
 *
 * @param interaction - The interaction object with v1_raw_google_diarized or blurb
 * @returns The computed raw interaction text with timestamps
 */
export function computeRawInteractionText(interaction: {
	v1_raw_google_diarized?: (typeof schema.interactions.$inferSelect)["v1_raw_google_diarized"];
	blurb?: string;
}): string {
	// Try to serialize from structured transcript
	if (interaction.v1_raw_google_diarized?.segments && Array.isArray(interaction.v1_raw_google_diarized.segments)) {
		return interaction.v1_raw_google_diarized.segments
			.map((segment) => {
				const startTime = formatTimestamp(segment.startTime);
				const endTime = formatTimestamp(segment.endTime);
				return `[${startTime} - ${endTime}] ${segment.speakerId}: ${segment.text}`;
			})
			.join("\n");
	}

	// Fallback to blurb
	return interaction.blurb ?? "";
}
