CREATE TABLE "revenues" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "revenues_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"amount" numeric(100, 2) NOT NULL,
	"associated_salesperson_id" integer NOT NULL,
	"closed_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "revenues" ADD CONSTRAINT "revenues_associated_salesperson_id_salespeople_id_fk" FOREIGN KEY ("associated_salesperson_id") REFERENCES "public"."salespeople"("id") ON DELETE cascade ON UPDATE no action;