CREATE TYPE "public"."impact_level" AS ENUM('high', 'medium', 'low');--> statement-breakpoint
CREATE TYPE "public"."notification_status" AS ENUM('unread', 'read', 'dismissed');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('info', 'warning', 'error', 'success');--> statement-breakpoint
CREATE TYPE "public"."sales_phase" AS ENUM('outreach', 'discovery', 'demo', 'close');--> statement-breakpoint
CREATE TYPE "public"."severity_level" AS ENUM('critical', 'major', 'minor');--> statement-breakpoint
CREATE TYPE "public"."trend_direction" AS ENUM('up', 'down', 'stable');--> statement-breakpoint
CREATE TABLE "interaction_objections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_objections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"interaction_id" integer NOT NULL,
	"objection_id" integer NOT NULL,
	"was_overcome" boolean DEFAULT false,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "interaction_objections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "interaction_pain_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interaction_pain_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"interaction_id" integer NOT NULL,
	"pain_point_id" integer NOT NULL,
	"was_resolved" boolean DEFAULT false,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "interaction_pain_points" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"message" text NOT NULL,
	"type" "notification_type" NOT NULL,
	"status" "notification_status" DEFAULT 'unread' NOT NULL,
	"priority" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"read_at" timestamp,
	"dismissed_at" timestamp,
	"user_id" text,
	"salesperson_id" integer,
	"interaction_id" integer,
	"flag_id" integer
);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "objections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "objections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text NOT NULL,
	"frequency" integer DEFAULT 0 NOT NULL,
	"trend" "trend_direction" DEFAULT 'stable' NOT NULL,
	"phase" "sales_phase" NOT NULL,
	"impact" "impact_level" NOT NULL,
	"total_calls_mentioned" integer DEFAULT 0,
	"overcome_percentage" numeric(5, 2),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"company_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "objections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "pain_points" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text NOT NULL,
	"frequency" integer DEFAULT 0 NOT NULL,
	"phase" "sales_phase" NOT NULL,
	"severity" "severity_level" NOT NULL,
	"is_prospect_pain" boolean NOT NULL,
	"total_calls_mentioned" integer DEFAULT 0,
	"resolution_percentage" numeric(5, 2),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"company_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pain_points" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interaction_objections" ADD CONSTRAINT "interaction_objections_interaction_id_interactions_id_fk" FOREIGN KEY ("interaction_id") REFERENCES "public"."interactions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_objections" ADD CONSTRAINT "interaction_objections_objection_id_objections_id_fk" FOREIGN KEY ("objection_id") REFERENCES "public"."objections"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_pain_points" ADD CONSTRAINT "interaction_pain_points_interaction_id_interactions_id_fk" FOREIGN KEY ("interaction_id") REFERENCES "public"."interactions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction_pain_points" ADD CONSTRAINT "interaction_pain_points_pain_point_id_pain_points_id_fk" FOREIGN KEY ("pain_point_id") REFERENCES "public"."pain_points"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_salesperson_id_salespeople_id_fk" FOREIGN KEY ("salesperson_id") REFERENCES "public"."salespeople"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_interaction_id_interactions_id_fk" FOREIGN KEY ("interaction_id") REFERENCES "public"."interactions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_flag_id_flags_id_fk" FOREIGN KEY ("flag_id") REFERENCES "public"."flags"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "objections" ADD CONSTRAINT "objections_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pain_points" ADD CONSTRAINT "pain_points_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;