CREATE TYPE "public"."prompt_setting_keys" AS ENUM('master', 'rating', 'flagging');--> statement-breakpoint
CREATE TABLE "system_prompt_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_prompt_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" "prompt_setting_keys" NOT NULL,
	"value" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "system_prompt_settings_key_unique" UNIQUE("key")
);
