CREATE TABLE "company_training_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_training_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company_id" integer NOT NULL,
	"onboarding_document" text,
	"ideal_responses" jsonb,
	"objection_handling_guide" jsonb,
	"product_positioning" text,
	"competitor_info" jsonb,
	"company_values" jsonb,
	"target_customer_profile" text,
	"sales_methodology" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "company_training_data_company_id_unique" UNIQUE("company_id")
);
--> statement-breakpoint
ALTER TABLE "company_training_data" ADD CONSTRAINT "company_training_data_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;