CREATE TYPE "public"."ai_context_types" AS ENUM('sales_language', 'objection_patterns', 'success_patterns', 'terminology', 'anti_patterns');--> statement-breakpoint
CREATE TYPE "public"."training_example_types" AS ENUM('flag_generation', 'roleplay_scenario', 'response_quality', 'insight_generation');--> statement-breakpoint
CREATE TYPE "public"."training_quality" AS ENUM('high', 'medium', 'low');--> statement-breakpoint
CREATE TABLE "company_ai_context" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_ai_context_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company_id" integer NOT NULL,
	"context_type" "ai_context_types" NOT NULL,
	"data" jsonb NOT NULL,
	"confidence" numeric(5, 4) NOT NULL,
	"sample_size" integer NOT NULL,
	"last_updated" timestamp DEFAULT now() NOT NULL,
	"version" text DEFAULT '1.0' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "training_examples" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_examples_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"company_id" integer NOT NULL,
	"example_type" "training_example_types" NOT NULL,
	"input_data" jsonb NOT NULL,
	"expected_output" jsonb NOT NULL,
	"feedback_signals" jsonb NOT NULL,
	"quality" "training_quality" NOT NULL,
	"source_flag_id" integer,
	"source_interaction_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "company_ai_context" ADD CONSTRAINT "company_ai_context_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training_examples" ADD CONSTRAINT "training_examples_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training_examples" ADD CONSTRAINT "training_examples_source_flag_id_flags_id_fk" FOREIGN KEY ("source_flag_id") REFERENCES "public"."flags"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training_examples" ADD CONSTRAINT "training_examples_source_interaction_id_interactions_id_fk" FOREIGN KEY ("source_interaction_id") REFERENCES "public"."interactions"("id") ON DELETE set null ON UPDATE no action;