CREATE TABLE "skills_assessments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "skills_assessments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"objection_handling_score" integer NOT NULL,
	"pricing_discussions_score" integer NOT NULL,
	"discovery_features_score" integer NOT NULL,
	"closing_score" integer NOT NULL,
	"assessment_data" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"interaction_id" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "skills_assessments" ADD CONSTRAINT "skills_assessments_interaction_id_interactions_id_fk" FOREIGN KEY ("interaction_id") REFERENCES "public"."interactions"("id") ON DELETE cascade ON UPDATE no action;