CREATE TABLE "training_scenarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_scenarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"skill_key" text NOT NULL,
	"scenario_id" text NOT NULL,
	"title" text NOT NULL,
	"difficulty" text NOT NULL,
	"duration" text NOT NULL,
	"participants" integer DEFAULT 2 NOT NULL,
	"context" text NOT NULL,
	"scenario" text NOT NULL,
	"objectives" jsonb NOT NULL,
	"common_objections" jsonb NOT NULL,
	"ideal_outcome" text NOT NULL,
	"ai_prompt" text NOT NULL,
	"prospect_data" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "training_scenarios_scenario_id_unique" UNIQUE("scenario_id")
);
