-- Add rep_highlights table for storing positive moments from call analysis
-- Used for aggregating top performer patterns and creating training clips

-- Create enum for skill areas
CREATE TYPE "rep_highlight_skill_area" AS ENUM (
  'objection_handling',
  'discovery',
  'rapport',
  'pricing',
  'closing',
  'active_listening',
  'value_articulation'
);

-- Create rep_highlights table
CREATE TABLE IF NOT EXISTS "rep_highlights" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "interaction_id" integer NOT NULL REFERENCES "interactions"("id") ON DELETE CASCADE,
  "created_at" timestamp DEFAULT now(),
  "skill_area" "rep_highlight_skill_area" NOT NULL,
  "technique" text NOT NULL,
  "verbatim_quote" text NOT NULL,
  "timestamp_start" text,
  "timestamp_end" text,
  "sales_phase" text,
  "impact" text,
  "clip_worthy_rating" integer,
  "clip_reason" text
);

-- Add index for efficient lookups by interaction
CREATE INDEX IF NOT EXISTS "rep_highlights_interaction_id_idx" ON "rep_highlights" ("interaction_id");

-- Add index for skill area aggregation
CREATE INDEX IF NOT EXISTS "rep_highlights_skill_area_idx" ON "rep_highlights" ("skill_area");
