-- Add workflow orchestration tables for async training session creation
-- Enables scalable processing of persona generation, agent creation, etc.

-- Create enums for workflow types and statuses
CREATE TYPE "workflow_type" AS ENUM (
  'scenario_session',
  'flag_session'
);

CREATE TYPE "workflow_status" AS ENUM (
  'pending',
  'processing',
  'completed',
  'failed'
);

CREATE TYPE "step_status" AS ENUM (
  'pending',
  'running',
  'completed',
  'failed'
);

CREATE TYPE "queue_status" AS ENUM (
  'pending',
  'locked',
  'completed',
  'failed'
);

-- Create workflow_state table
CREATE TABLE IF NOT EXISTS "workflow_state" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "workflow_type" "workflow_type" NOT NULL,
  "workflow_id" text NOT NULL,
  "status" "workflow_status" NOT NULL DEFAULT 'pending',
  "current_step" text,
  "metadata" jsonb,
  "result" jsonb,
  "error" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  "completed_at" timestamp
);

-- Create workflow_step_runs table
CREATE TABLE IF NOT EXISTS "workflow_step_runs" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "workflow_state_id" integer NOT NULL REFERENCES "workflow_state"("id") ON DELETE CASCADE,
  "step_name" text NOT NULL,
  "status" "step_status" NOT NULL DEFAULT 'pending',
  "input_data" jsonb,
  "output_data" jsonb,
  "error" text,
  "started_at" timestamp,
  "completed_at" timestamp,
  "duration_ms" integer,
  "created_at" timestamp DEFAULT now() NOT NULL
);

-- Create workflow_queue table
CREATE TABLE IF NOT EXISTS "workflow_queue" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "workflow_state_id" integer NOT NULL REFERENCES "workflow_state"("id") ON DELETE CASCADE,
  "priority" integer NOT NULL DEFAULT 0,
  "status" "queue_status" NOT NULL DEFAULT 'pending',
  "attempts" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL DEFAULT 3,
  "scheduled_at" timestamp DEFAULT now() NOT NULL,
  "locked_at" timestamp,
  "locked_by" text,
  "created_at" timestamp DEFAULT now() NOT NULL,
  UNIQUE ("workflow_state_id")
);

-- Create indexes for efficient queries
CREATE INDEX IF NOT EXISTS "workflow_state_status_created_at_idx" ON "workflow_state" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "workflow_state_type_id_idx" ON "workflow_state" ("workflow_type", "workflow_id");
CREATE INDEX IF NOT EXISTS "workflow_step_runs_state_id_started_at_idx" ON "workflow_step_runs" ("workflow_state_id", "started_at");
CREATE INDEX IF NOT EXISTS "workflow_queue_status_priority_scheduled_at_idx" ON "workflow_queue" ("status", "priority", "scheduled_at");

