-- Meeting Prep Feature: AI-powered meeting preparation with guides, chat, and voice roleplay
DO $$ BEGIN
    CREATE TYPE "public"."meeting_prep_status" AS ENUM('setup', 'ready', 'practiced');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."meeting_prep_call_type" AS ENUM('discovery', 'demo', 'negotiation', 'closing', 'follow_up');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "meeting_preps" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "meeting_preps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "salesperson_id" integer NOT NULL,
    "company_id" integer NOT NULL,
    "prospect_company" text NOT NULL,
    "prospect_contact_name" text,
    "prospect_contact_role" text,
    "prospect_industry" text,
    "prospect_company_size" text,
    "prospect_website" text,
    "call_type" "meeting_prep_call_type" NOT NULL,
    "meeting_goal" text NOT NULL,
    "known_pain_points" jsonb,
    "previous_interactions" text,
    "notes" text,
    "prep_guide" text,
    "chat_history" jsonb,
    "agent_id" text,
    "agent_prompt" jsonb,
    "status" "meeting_prep_status" DEFAULT 'setup' NOT NULL,
    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
);

DO $$ BEGIN
    ALTER TABLE "meeting_preps" ADD CONSTRAINT "meeting_preps_salesperson_id_salespeople_id_fk" FOREIGN KEY ("salesperson_id") REFERENCES "public"."salespeople"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "meeting_preps" ADD CONSTRAINT "meeting_preps_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Index for faster queries by salesperson
CREATE INDEX IF NOT EXISTS "meeting_preps_salesperson_id_idx" ON "meeting_preps" ("salesperson_id");
CREATE INDEX IF NOT EXISTS "meeting_preps_company_id_idx" ON "meeting_preps" ("company_id");
