-- CRM Integration: Store OAuth connections to external CRMs (HubSpot, Zoho, etc.)
-- Read-only integration to enrich meeting prep and company context

DO $$ BEGIN
    CREATE TYPE "public"."crm_provider" AS ENUM('hubspot', 'zoho', 'agilecrm');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "public"."crm_connection_status" AS ENUM('connected', 'disconnected', 'error', 'expired');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "crm_connections" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "crm_connections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "company_id" integer NOT NULL,
    "provider" "crm_provider" NOT NULL,

    -- OAuth tokens (should be encrypted in production)
    "access_token" text NOT NULL,
    "refresh_token" text,
    "token_expires_at" timestamp,

    -- Provider account info
    "provider_account_id" text,
    "provider_account_name" text,
    "connected_user_email" text,

    -- Sync status
    "status" "crm_connection_status" DEFAULT 'connected' NOT NULL,
    "last_sync_at" timestamp,
    "sync_error" text,

    -- Stats
    "contacts_count" integer DEFAULT 0,
    "companies_count" integer DEFAULT 0,
    "deals_count" integer DEFAULT 0,

    "created_at" timestamp DEFAULT now() NOT NULL,
    "updated_at" timestamp DEFAULT now() NOT NULL
);

DO $$ BEGIN
    ALTER TABLE "crm_connections" ADD CONSTRAINT "crm_connections_company_id_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS "crm_connections_company_id_idx" ON "crm_connections" ("company_id");

-- Unique constraint: one connection per provider per company
CREATE UNIQUE INDEX IF NOT EXISTS "crm_connections_company_provider_idx" ON "crm_connections" ("company_id", "provider");
