-- Create training session status enum
DO $$ BEGIN
 CREATE TYPE "training_session_status" AS ENUM('in_progress', 'completed');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Create training sessions completed table
CREATE TABLE IF NOT EXISTS "training_sessions_completed" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_sessions_completed_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scenario_id" integer NOT NULL,
	"salesperson_id" integer NOT NULL,
	"agent_id" text,
	"agent_prompt" jsonb,
	"status" "training_session_status" DEFAULT 'in_progress' NOT NULL,
	"started_at" timestamp DEFAULT now() NOT NULL,
	"completed_at" timestamp,
	"training_session" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- Add foreign key constraints
DO $$ BEGIN
 ALTER TABLE "training_sessions_completed" ADD CONSTRAINT "training_sessions_completed_scenario_id_training_scenarios_id_fk" FOREIGN KEY ("scenario_id") REFERENCES "training_scenarios"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

DO $$ BEGIN
 ALTER TABLE "training_sessions_completed" ADD CONSTRAINT "training_sessions_completed_salesperson_id_salespeople_id_fk" FOREIGN KEY ("salesperson_id") REFERENCES "salespeople"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint

-- Partial unique index: only one in_progress session per salesperson+scenario
CREATE UNIQUE INDEX IF NOT EXISTS unique_in_progress_session_idx
ON training_sessions_completed (salesperson_id, scenario_id)
WHERE status = 'in_progress';
